name: Pull Request


on:
  pull_request:
    types: [opened, reopened, synchronize]
    
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This is required for git show-ref to work

      - name: Build and lint
        uses: .github/actions/build-and-lint.yaml

