name: Pull Request


on:
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and lint
        uses: ./.github/actions/build-and-lint.yaml

