name: Release
run-name : Release (push) the world chain deployer image.


on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  push:
    branches:
        - "develop"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  packages: write # This is required to publish to github package repository
  attestations: write # This is required to publish to github package repository

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: world-chain-deployer-image

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build and push deployer image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: build/package/frontier-world.dockerfile
          context: .
          platforms: |
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build_and_push.outputs.digest }}
          push-to-registry: true
