name: SmokeTest


on:
  push:
    branches:
      - "*"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  BUILD_COMMIT: ${{ github.sha }}
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
  IMAGE_NAME: world-chain-deployer-image-TEST

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and load deployer image
        id: build_and_load
        uses: docker/build-push-action@v5
        # if: github.event_name == 'push' && github.ref_name == 'main'
        with:
          push: false
          load: true
          file: build/package/frontier-world.dockerfile
          context: .
          platforms: |
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run local anvil node
        run: |
          ./scripts/run-local-node.sh &

      - name: Run deployer image
        run: |
          echo "Will run something like docker run for the image"

      - name: Running smoke tests on local chain
        run: |
          echo "Will run something like ./scripts/run-smoke-tests.sh"


